Repository FRONTENDBOOTCAMP-13th/JS-15-Semicolon, pull requests merged in 2025-05, with the labels that each got.

#3 Chore/setup ts
  eslint.config.js
  package-lock.json
  package.json
  src/main.ts
  tsconfig.json
Labels: 🏃 Feature

#4 :whale: chore: PR 템플릿 추가
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: 📝 Documentation

#5 :whale: chore: PR 템플릿 위치 이동
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚒️BugFix

#13 :test_tube: test: PR 테스트
  test-hj.js
Labels: 🏃 Feature

#14 :fire: remove: PR 템플릿 테스트 파일 삭제
  test-ay.js
  test-hj.js
  test-jlim.md
  test-yong.js
Labels: 🏃 Feature

#16 :tada: init: Tailwind CSS 초기 세팅 완료
  package-lock.json
  package.json
  src/style.css
  vite.config.js
Labels: 🏃 Feature

#17 :sparkles: feat: 기본 컴포넌트 구조 세팅
  src/components/footer.html
  src/components/header.html
  src/pages/detail-page.html
  src/pages/main-page.html
  src/ts/festivalApi.ts
  src/ts/kakaoApi.ts
  src/ts/weatherApi.ts
Labels: 🎉 Init

#18 Feat/tour-api-cnt
  src/components/card.html
  src/main.ts
  src/ts/festivalApi.ts
  tsconfig.json
  vite-env.d.ts
  vite.config.js
Labels: 🏃 Feature

#20 Feature/form set
  src/components/card.html
  src/ts/festivalApi.ts
Labels: 🏃 Feature

#23 Feat/card component
  package-lock.json
  package.json
  src/components/card.html
  src/main.ts
  src/style.css
  src/ts/festivalApi.ts
  vite.config.js
Labels: 🏃 Feature, 🎉 Init

#24 Style/card form
  src/components/card.html
  src/ts/festivalApi.ts
Labels: ⚒️BugFix, 🏃 Feature

#25 :test_tube: test: 카드 컴포넌트 마크업 테스트 코드 삭제
  src/components/card.html
Labels: ♻️Refactor

#28 :memo: docs: festivalApi.ts 내 주석 정비 및 코드 가독성 향상
  src/ts/festivalApi.ts
Labels: 📝 Documentation

#29 :sparkles: feat: index page 생성 및 컴포넌트 링크 추가
  index.html
  src/main.js
Labels: 🏃 Feature

#31 :bug: fix: date input 날짜 표시 형식 변경
  src/ts/festivalApi.ts
Labels: ⚒️BugFix

#33 Feature/detail page
  src/components/detail.html
  src/ts/detail.ts
  src/ts/festivalApi.ts
Labels: 🏃 Feature

#34 Feature/kakaomap api
  index.html
  package-lock.json
  package.json
  src/components/kakaomap.html
  src/main.ts
  src/ts/kakaoApi.ts
Labels: 🏃 Feature

#35 :sparkles: feat: 검색 조건 및 결과 localStorage로 복원 기능 추가
  src/ts/festivalApi.ts
Labels: 🏃 Feature

#41 Feat/signup validation
  package-lock.json
  package.json
  src/components/login.html
  src/components/signup.html
  src/ts/api/festivalApi.ts
  src/ts/auth/auth.ts
  tsconfig.json
Labels: 🏃 Feature

#46 Feat/card rendering
  src/ts/api/festivalApi.ts
Labels: 🏃 Feature

#43 :bug: fix: 지도 객체 사이즈 조정 및 중복 로딩 에러 수정
  src/components/kakaomap.html
  src/ts/api/kakaoApi.ts
Labels: ⚒️BugFix

#50 Refactor/card components
  src/ts/api/festivalApi.ts
  src/ts/detail.ts
Labels: 🏃 Feature, ♻️Refactor

#53 Feature/connect api
  src/components/card.html
  src/components/detail.html
  src/ts/api/shortWeatherApi.ts
  src/ts/api/weatherApi.ts
  src/ts/detail.ts
  src/ts/weather.ts
Labels: 🏃 Feature

#55 Feat/51 bookmark setting
  src/components/bookmark-component.html
  src/ts/bookmark.ts
Labels: 🏃 Feature

#57 Feature/connect-kakao-api
  src/components/detail.html
  src/ts/api/kakaoApi.ts
  src/ts/detail.ts
Labels: ⚒️BugFix, 🏃 Feature

#58 Fix/56 weather layout fix
  src/components/weather-test.html
  src/ts/api/shortWeatherApi.ts
  src/ts/bookmark.ts
  src/ts/weather.ts
Labels: ⚒️BugFix

#65 Refactor/card component
  src/components/card.html
  src/ts/api/festivalApi.ts
  src/ts/bookmark.ts
  src/ts/detail.ts
Labels: 🏃 Feature

#66 Feat/64 header footer detail
  src/components/footer.html
  src/components/header.html
  src/ts/api/shortWeatherApi.ts
  src/ts/api/weatherApi.ts
Labels: 🏃 Feature

#69 Refactor/folder structure
  src/components/card.html
  src/components/detail.html
  src/counter.js
  src/javascript.svg
  src/main.js
  src/main.ts
  src/ts/api/festivalApi.ts
  src/ts/api/fetchFestival.ts
  src/ts/auth/register.ts
  src/ts/auth/userStorage.ts
  src/ts/features/bookmark.ts
  src/ts/features/carousel.ts
  src/ts/features/detail.ts
  src/ts/features/filter.ts
  src/ts/features/weather.ts
  src/ts/render/festivalRenderer.ts
Labels: ⚒️BugFix, ♻️Refactor

#70 Feat/67 top btn
  src/assets/icon/top.svg
  src/components/footer.html
  src/components/header.html
  src/components/top-btn.html
  src/ts/top-btn.ts
Labels: 🏃 Feature

#74 :bug: fix: 배포 테스트 config 파일 설정
  index.html
  vite.config.js
Labels: ♻️Refactor

#73 Fix: carousel route error
  src/components/carousel.html
Labels: ⚒️BugFix

#77 :bug: fix: proxy 경로 수정
  src/ts/api/festivalApi.ts
Labels: ⚒️BugFix

#78 :bug: fix: api 서버 url 주소 누락
  src/ts/api/festivalApi.ts
Labels: ⚒️BugFix

#79 Deploy/proxy setting
  netlify.toml
  src/ts/api/festivalApi.ts
Labels: ⚒️BugFix

#80 Deploy/proxy setting
  netlify.toml
Labels: ⚒️BugFix

#88 :sparkles: feat: 상세 페이지(detail.html) Vite 빌드 경로에 추가
  vite.config.js
Labels: ⚒️BugFix

#91 Feat/63 bookmark local storage
  index.html
  src/components/card.html
  src/ts/features/bookmark.ts
Labels: 🏃 Feature

#92 :bug: fix: 첫 렌더링 프록시 서버 연결
  src/ts/api/festivalApi.ts
Labels: ⚒️BugFix

#94 Fix/api proxy connect
  index.html
  src/ts/auth/auth.ts
Labels: 🏃 Feature

#96 Fix/carousel image route&style
  src/assets/img/hero-carousel-image1.webp
  src/assets/img/hero-carousel-image2.webp
  src/assets/img/hero-carousel-image6.webp
  src/ts/features/carousel.ts
Labels: ⚒️BugFix, 💄style

#97 Fix/detail page connect
  src/components/detail.html
  src/main.ts
  vite.config.js
Labels: ⚒️BugFix

#99 :sparkles: feat: favicon 추가
  index.html
  public/apple-touch-icon.png
  public/favicon(circle).svg
  public/favicon(square).svg
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/site.webmanifest
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
Labels: 🏃 Feature

#101 Feat/72 footer edit
  src/components/detail-design.html
  src/components/footer.html
  src/components/header.html
  src/components/reset-btn.html
  src/components/top-btn.html
  src/ts/features/filter.ts
  src/ts/features/top-btn.ts
Labels: 🏃 Feature

#103 :lipstick: style: 카카오맵 마커 이미지 변경
  public/marker(red).png
  public/marker(white).png
  src/ts/api/kakaoApi.ts
Labels: ♻️Refactor, 💄style

#107 Style/index layout
  src/assets/icon/back-btn.svg
  src/components/detail.html
  src/components/login.html
  src/components/signup.html
Labels: ♻️Refactor

#106 style: index 헤더 디자인 수정
  index.html
  src/components/detail.html
Labels: 🏃 Feature

#110 Feat/fix weatherApi
  src/ts/api/weatherApi.ts
Labels: ⚒️BugFix

#109 Fix/bookmark filtering
  index.html
  src/main.ts
  src/ts/features/bookmark.ts
Labels: ⚒️BugFix

#112 Style/detail layout
  index.html
  src/components/detail-design.html
  src/components/header.html
  src/ts/auth/header.ts
  src/ts/features/detail.ts
Labels: 🏃 Feature

#116 :lipstick: style: 캐러셀 폰트 크기/글 수정
  src/ts/features/carousel.ts
Labels: 💄style

#120 :lipstick: style: 푸터 스타일 변경
  index.html
Labels: 🏃 Feature

#121 Fix/kakaomap changeorigin
  src/ts/api/kakaoApi.ts
  src/ts/features/detail.ts
Labels: ⚒️BugFix

#122 Fix: reset-btn 버그 수정
  src/ts/features/bookmark.ts
  src/ts/features/filter.ts
Labels: ⚒️BugFix

#123 Refactor/detail page
  src/assets/icon/arrow.svg
  src/components/detail.html
Labels: ⚒️BugFix, 🏃 Feature

#127 Refactor/auth page
  src/components/detail.html
  src/ts/auth/auth.ts
  vite.config.js
Labels: ⚒️BugFix, 🏃 Feature

#129 Feat/128 loading
  index.html
  src/main.ts
  src/ts/render/festivalRenderer.ts
Labels: 🏃 Feature

#132 Refactor/index page
  index.html
  src/ts/render/festivalRenderer.ts
Labels: ⚒️BugFix, 🏃 Feature, ♻️Refactor

#133 Feat/130 top btn edit
  index.html
  src/assets/icon/top.svg
  src/ts/features/top-btn.ts
  src/ts/render/festivalRenderer.ts
Labels: 🏃 Feature

#137 Qa/index page
  index.html
  src/ts/features/carousel.ts
  src/ts/render/festivalRenderer.ts
Labels: ⚒️BugFix, 💄style

#140 Qa/detail page
  src/components/detail.html
  src/ts/api/shortWeatherApi.ts
  src/ts/api/weatherApi.ts
Labels: ⚒️BugFix, ♻️Refactor

#139 Feat/138 weather screen reader
  src/ts/api/shortWeatherApi.ts
  src/ts/api/weatherApi.ts
  src/ts/features/detail.ts
Labels: 🚀 Accessibility

#141 Qa/auth page
  src/components/login.html
  src/components/signup.html
Labels: ⚒️BugFix, ♻️Refactor

#142 Fix/bookmark filtering
  src/main.ts
  src/ts/features/bookmark.ts
  src/ts/render/festivalRenderer.ts
Labels: ⚒️BugFix

#149 Feat/ 북마크 버튼 로그인 페이지로 이동 컨펌 생성
  src/ts/features/bookmark.ts
Labels: 🏃 Feature

#152 Feat/signup page features
  src/ts/auth/auth.ts
Labels: ⚒️BugFix, 🏃 Feature

#157 feat: 북마크 렌더 버튼에 컨펌 추가
  src/main.ts
Labels: 🏃 Feature

#160 🐛 fix: 단기예보 새벽 데이터
  src/ts/api/shortWeatherApi.ts
Labels: ⚒️BugFix
